### ISSUE TITLE
How you define observation of agents?

### ISSUE THREAD

**Issue by woaipichuli** [mlii/mfrl#3]
I have read the paper: Mean Field Multi-Agent Reinforcement Learning. However, I wonder how you define the observation of agents, since I did find corresponding description in the paper. Do the agents are able to get a full observation or local observation, especially in the battle game?

**Comment by KornbergFresnel** [comment]
@woaipichuli Hi, the agents get local observation of an area with size of 13*13, and the observation of an agent includes some attributions (like HP, friend or enemy) of other agents which occur in the local view. You can get more information about battle game from [MAgent](https://github.com/geek-ai/MAgent)
