### ISSUE TITLE
how you define the markov state?

### ISSUE THREAD

**Issue by lyers179** [mlii/mfrl#5]
I have read the paper Mean Field Multi-Agent Reinforcement Learning,agent's state is global or individual？would you mind explaining me the battle game'markov state.Thx！

**Comment by KornbergFresnel** [comment]
@lyers179 hi, the agent's state is individual as we described in the paper, and the state of agent in the battle game includes observation and feature vector. For more information, pls visit https://github.com/mlii/mfrl/issues/3 or read https://github.com/geek-ai/MAgent.
