### ISSUE TITLE
Is the `type.move_base` a replication mistake?

### ISSUE THREAD

**Issue by JloveU** [mlii/mfrl#7]
File: `examples/battle_model/src/gridworld/GridWorld.cc`.
Line: 423, 432, 447.

Is the `type.move_base` a replication mistake?
According to my understanding, this should be replaced by `type.turn_base`.

Thanks!

**Comment by KornbergFresnel** [comment]
@JloveU  it is not a mistake, because the real direction is corresponding to the value of  `act - type.move_base`.
